In [18]:
import numpy as np
from itertools import product

def generate_binary_vectors(length):
    """Генерація всіх можливих бінарних векторів заданої довжини."""
    return list(product([0, 1], repeat=length))

def target_function(q, binary_vectors):
    """Цільова функція для мінімізації."""
    return (1/(2**10)) * sum((q - np.sum(binary_vector))**2 for binary_vector in binary_vectors)

def minimize_function(binary_vectors):
    """Мінімізація цільової функції."""
    best_q = None
    best_value = float('inf')

    for q_candidate in range(6):  # q приймає значення від 0 до 5 включно
        current_value = target_function(q_candidate, binary_vectors)
        if current_value < best_value:
            best_value = current_value
            best_q = q_candidate

    return best_q, best_value

if __name__ == "__main__":
    binary_vectors = generate_binary_vectors(5)
    optimal_q, minimal_value = minimize_function(binary_vectors)

    print("Оптимальне значення q:", optimal_q)
    print("Мінімальне значення функції:", minimal_value)
    print("Бінарні згенеровані вектори:", binary_vectors)

Оптимальне значення q: 2
Мінімальне значення функції: 0.046875
Бінарні згенеровані вектори: [(0, 0, 0, 0, 0), (0, 0, 0, 0, 1), (0, 0, 0, 1, 0), (0, 0, 0, 1, 1), (0, 0, 1, 0, 0), (0, 0, 1, 0, 1), (0, 0, 1, 1, 0), (0, 0, 1, 1, 1), (0, 1, 0, 0, 0), (0, 1, 0, 0, 1), (0, 1, 0, 1, 0), (0, 1, 0, 1, 1), (0, 1, 1, 0, 0), (0, 1, 1, 0, 1), (0, 1, 1, 1, 0), (0, 1, 1, 1, 1), (1, 0, 0, 0, 0), (1, 0, 0, 0, 1), (1, 0, 0, 1, 0), (1, 0, 0, 1, 1), (1, 0, 1, 0, 0), (1, 0, 1, 0, 1), (1, 0, 1, 1, 0), (1, 0, 1, 1, 1), (1, 1, 0, 0, 0), (1, 1, 0, 0, 1), (1, 1, 0, 1, 0), (1, 1, 0, 1, 1), (1, 1, 1, 0, 0), (1, 1, 1, 0, 1), (1, 1, 1, 1, 0), (1, 1, 1, 1, 1)]


In [19]:
import numpy as np
from scipy.spatial import ConvexHull

def generate_independent_vectors(N):
    """Генерація N тривимірних незалежних векторів."""
    np.random.seed(42)  # для відтворюваності результатів
    first_two_coords = np.random.exponential(scale=1, size=(N, 2))
    third_coord = np.random.normal(size=N)
    independent_vectors = np.column_stack((first_two_coords, third_coord))
    return independent_vectors

def kozinec_algorithm(independent_vectors):
    """Алгоритм Козинця для пошуку розділяючого вектора."""
    hull = ConvexHull(independent_vectors)
    separating_vector = hull.equations[:, :-1].mean(axis=0)
    return separating_vector / np.linalg.norm(separating_vector)

if __name__ == "__main__":
    N = 50
    vectors = generate_independent_vectors(N)
    
    separating_vector = kozinec_algorithm(vectors)

    print("Згенеровані вектори:")
    print(vectors)
    
    print("\nРозділяючий вектор з опуклої оболонки:")
    print(separating_vector)

Згенеровані вектори:
[[ 0.46926809  3.01012143  0.08704707]
 [ 1.31674569  0.91294255 -0.29900735]
 [ 0.16962487  0.16959629  0.09176078]
 [ 0.05983877  2.01123086 -1.98756891]
 [ 0.91908215  1.23125006 -0.21967189]
 [ 0.02079931  3.50355748  0.35711257]
 [ 1.78642954  0.23868763  1.47789404]
 [ 0.20067899  0.20261142 -0.51827022]
 [ 0.36275373  0.74392783 -0.8084936 ]
 [ 0.56553707  0.34422299 -0.50175704]
 [ 0.94637087  0.15023453  0.91540212]
 [ 0.34551551  0.45627722  0.32875111]
 [ 0.60893469  1.53793601 -0.5297602 ]
 [ 0.22273586  0.72202916  0.51326743]
 [ 0.89750472  0.04756385  0.09707755]
 [ 0.93533302  0.18696125  0.96864499]
 [ 0.06726393  2.97368779 -0.70205309]
 [ 3.37063034  1.65233157 -0.32766215]
 [ 0.36328786  0.10277732 -0.39210815]
 [ 1.15275076  0.58009084 -1.46351495]
 [ 0.13015223  0.68354723  0.29612028]
 [ 0.03499372  2.40042289  0.26105527]
 [ 0.29945778  1.0862558   0.00511346]
 [ 0.37354658  0.7341109  -0.23458713]
 [ 0.7912238   0.2043886  -1.41537074]
 [ 3

In [23]:
import numpy as np
from scipy.stats import norm


def generate_data(n, p_k1, a1, a2):
    """Генерація випадкових величин згідно з умовами задачі."""
    k_states = np.random.choice([1, 2], size=n, p=[p_k1, 1 - p_k1])
    means = np.where(k_states == 1, a1, a2)
    data = np.random.normal(loc=means, scale=1)
    return data, k_states

def expectation_maximization(data, max_iterations=1000, tol=0.001):
    """Алгоритм самонавчання."""
    n = len(data)
    p_k1 = 0.5
    p_k2 = 1 - p_k1
    a1 = 1
    a2 = 2

    for iteration in range(max_iterations):
        # Expectation step
        pdf_k1 = norm.pdf(data, loc=a1, scale=1)
        pdf_k2 = norm.pdf(data, loc=a2, scale=1)
        gamma_k1 = p_k1 * pdf_k1 / (p_k1 * pdf_k1 + p_k2 * pdf_k2)
        gamma_k2 = p_k2 * pdf_k2 / (p_k1 * pdf_k1 + p_k2 * pdf_k2)

        # Maximization step
        p_k1_new = np.mean(gamma_k1)
        p_k2_new = np.mean(gamma_k2)
        
        f1 = norm.pdf(data, loc=0, scale=1)
        f2 = norm.pdf(data, loc=1, scale=1)
        f3 = norm.pdf(data, loc=2, scale=1)
        f4 = norm.pdf(data, loc=3, scale=1)
        
        
        func1 = np.sum(gamma_k1 *np.log(f1))
        func2 = np.sum(gamma_k1 *np.log(f2))
        if (func1 > func2): 
            a1_new = 0
        else: 
            a1_new = 1
            
        func3 = np.sum(gamma_k2 *np.log(f3))
        func4 = np.sum(gamma_k2 *np.log(f4))
        if (func3 > func4): 
            a2_new = 2
        else: 
            a2_new = 3

        # Check convergence
        if np.abs(p_k1_new - p_k1) < tol and  a1_new - a1 == 0 and \
           np.abs(p_k2_new - p_k2) < tol and a2_new - a2 == 0:
            break

        # Update parameters
        p_k1, p_k2, a1, a2 = p_k1_new, p_k2_new, a1_new, a2_new

    return p_k1, p_k2, a1, a2

if __name__ == "__main__":
    np.random.seed(42)  # для відтворюваності результатів
    n = 100
    p_k1_true = 1/3
    a1_true = 0
    a2_true = 3

    data, true_k_states = generate_data(n, p_k1_true, a1_true, a2_true)

    # Ініціалізація параметрів 
    p_k1_init = 0.5
    a1_init = 1
    a2_init = 2

    # Застосування алгоритму самонавчання
    p_k1_hat, p_k2_hat, a1_hat, a2_hat = expectation_maximization(data)

    print("Справжні значення:")
    print("P(k=1) =", p_k1_true, "a1 =", a1_true)
    print("P(k=2) =", 1 - p_k1_true, "a2 =", a2_true)

    print("\nОцінені значення:")
    print("P(k=1) =", p_k1_hat, "a1 =", a1_hat)
    print("P(k=2) =", p_k2_hat, "a2 =", a2_hat)

Справжні значення:
P(k=1) = 0.3333333333333333 a1 = 0
P(k=2) = 0.6666666666666667 a2 = 3

Оцінені значення:
P(k=1) = 0.5341101250146805 a1 = 1
P(k=2) = 0.4658898749853195 a2 = 3
